ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:534420079206:certificate/cad9de2a-623f-4579-a24b-9f10004c449c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/success-codes: '200,301'
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  hosts:
  - host: gong-test.conects.com
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: conects-gong
          port:
            number: 80
  - host: gongoff-test.conects.com
    paths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: ssl-redirect
          port:
            name: use-annotation
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: conects-gong
          port:
            number: 80
  - host: gangnam-test.conects.com
    paths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: ssl-redirect
          port:
            name: use-annotation
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: conects-gong
          port:
            number: 80
  - host: daegu-test.conects.com
    paths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: ssl-redirect
          port:
            name: use-annotation
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: conects-gong
          port:
            number: 80
  - host: bsdangi-test.conects.com
    paths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: ssl-redirect
          port:
            name: use-annotation
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: conects-gong
          port:
            number: 80
  - host: "test-plab.conects.com"
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: conects-plab
          port:
            number: 80
  - host: "my-test.conects.com"
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: conects-my
          port:
            number: 80
