{{- if .Values.autoscaling.enabled  | default false}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "01-conects-gong.fullname" . }}
  labels: 
    {{- include "01-conects-gong.labels" . | nindent 4 }}
spec: 
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "01-conects-gong.selectorLabels" . | nindent 6 }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "01-conects-gong.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        env: 
          {{- toYaml .Values.env | nindent 10 }}
          - name: DD_SERVICE_MAPPING
            value: mysqli:st-{{ .Release.Name }}-rds-cluster
        image: "534420079206.dkr.ecr.ap-northeast-2.amazonaws.com/01_{{ include "imageAddress" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.httpPort }}
          protocol: TCP
        - name: https
          containerPort: {{ .Values.service.httpsPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10}}
        {{- with .Values.volumeMounts }}
        volumeMounts:
        {{- range .}}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
        {{- end }}
        {{- end }}
        terminationMessagePath: {{ .Values.terminationMessagePath}}
        terminationMessagePolicy: {{ .Values.terminationMessagePolicy}}
      {{- with .Values.initContainers}}
      initContainers:
      - env:
        {{- toYaml .env | nindent 10}}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8}}
      {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{  .Values.restartPolicy }}
      schedulerName: {{  .Values.schedulerName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds}}
{{- end}}